#!/bin/bash

# Yeoman and friends install
## node.js install
sudo apt-get -y install python-software-properties
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:chris-lea/node.js
sudo apt-get update
sudo apt-get -y install nodejs
sudo apt-get -y install npm

## ruby install
sudo apt-get -y install ruby1.9.3

## yeoman friends
sudo gem install compass
sudo apt-get install -y libjpeg-turbo-progs
sudo apt-get install -y optipng

## yeoman itself
sudo npm install -g yeoman 

# testacular
sudo npm install -g testacular

# webstorm install
## download & extract
cd ~/downloads
wget http://download.jetbrains.com/webide/WebStorm-5.0.4.tar.gz
tar xfz WebStorm-*.tar.gz

## move to install dir
mkdir ~/utils
mv WebStorm-121.390 ~/utils/WebStorm

## install java 6
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java6-installer

## AddOns
