#!/bin/bash

# Basic installation
sudo apt-get -y install git
sudo apt-get -y install ssh
sudo apt-get -y install tmux
sudo apt-get -y install zsh

# user init

# CasperJs install
## download & extract
mkdir ~/downloads
cd ~/downloads
wget http://phantomjs.googlecode.com/files/phantomjs-1.8.1-linux-i686.tar.bz2
tar -jxvf phantomjs-1.8.1-linux-i686.tar.bz2
## move to install dir
mkdir ~/utils
mv phantomjs-1.8.1-linux-i686 ~/utils/phantomjs
## setup in path
sudo ln -s /home/wosinekm/utils/phantomjs/bin/phantomjs /usr/local/bin/phantomjs

## AddOns
sudo apt-get -y install libfreetype6 libfreetype6-dev
sudo apt-get -y install fontconfig
